# Generated by Django 5.2.6 on 2025-10-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default.jpg', null=True, upload_to='profile_photos/', verbose_name='Foto de Perfil'),
        ),
    ]
