# Generated by Django 5.2.6 on 2025-09-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_terms_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='static/users/images/default_profile.jpg', null=True, upload_to='profile_photos/', verbose_name='Foto de Perfil'),
        ),
    ]
